apiVersion: v1
data:
  browsers.yaml: |
    chrome:
      default: "69.0"
      versions:
        69.0:
          image: "selenium/standalone-chrome:3.14.0-helium"
          port: 4444
          healthCheck: "/wd/hub"
          baseURL: "/wd/hub"
        68.0:
          image: "selenium/standalone-chrome:3.14.0-curium"
          port: 4444
          healthCheck: "/wd/hub"
          baseURL: "/wd/hub"
        67.0:
          image: "selenoid/chrome:67.0"
          port: 4444
          healthCheck: ""
          baseURL: ""
        debug:
          image: "selenium/standalone-chrome-debug:3.14.0-helium"
          port: 4444
          healthCheck: "/wd/hub"
          baseURL: "/wd/hub"
          vncPort: 5900
    firefox:
      default: "60.0"
      versions:
        60.0:
          image: "selenium/standalone-firefox:3.12.0"
          port: 4444
          healthCheck: "/wd/hub"
          baseURL: "/wd/hub"
        59.0:
          image: "selenium/standalone-firefox:3.11.0"
          port: 4444
          healthCheck: "/wd/hub"
          baseURL: "/wd/hub"
kind: ConfigMap
metadata:
  name: sersan-browsers
  namespace: sersan