# Default values for sersan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

namespace: sersan

image:
  repository: dimasaryoprakoso/sersan
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 4444

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 20Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccountName: sersan